### ISSUE TITLE
Relicense documentation to Creative Commons Attribution-ShareAlike 4.0 International License.

### ISSUE THREAD

**Issue by xf8b** [xf8b/xf8bot#29]
Please comment below this message `I agree to the relicense of xf8bot's documentation to Creative Commons Attribution-ShareAlike 4.0 International License.` if you agree, or `I do not agree to the relicense of xf8bot's documentation to Creative Commons Attribution-ShareAlike 4.0 International License.`
@xf8b 
@zAG6z 
@BHLoneWolf0

**Comment by xf8b** [comment]
I agree to the relicense of xf8bot's documentation to Creative Commons Attribution-ShareAlike 4.0 International License.

**Comment by BHLoneWolf0** [comment]
I agree

**Comment by zAG6z** [comment]
I agree to the relicense of xf8bot's documentation to Creative Commons Attribution-ShareAlike 4.0 International License.

**Comment by xf8b** [comment]
ok cool thanks

**Comment by xf8b** [comment]
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:cc="http://creativecommons.org/ns#" class="license-text"><a rel="cc:attributionURL" property="dct:title" href="https://xf8b.github.io/xf8bot/docs/">xf8bot Documentation</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/xf8b/">xf8b</a> is licensed under <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" /><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" /><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" /></a></p>
