### ISSUE TITLE
non bot administrators can use bot administrator commands

### ISSUE THREAD

**Issue by xf8b** [xf8b/xf8bot#32]
xf8b pls fix

**Comment by zAG6z** [comment]
i love how you write a issue on github instead of actually trying to fix it lmfao

**Comment by xf8b** [comment]
no

**Comment by xf8b** [comment]
irritate

**Comment by zAG6z** [comment]
get good

**Comment by xf8b** [comment]
ok

**Comment by xf8b** [comment]
😎  i locked

**Comment by xf8b** [comment]
😎  i unlocked

**Comment by zAG6z** [comment]
ok i will star again

**Comment by xf8b** [comment]
hopefully fixed, please update your xf8bot image locally by running `docker pull ghcr.io/xf8b/xf8bot`
